apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
data:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "secret/*" }}
  {{ base $path }}: |-
    {{ $root.Files.Get $path | b64enc }}
  {{- end }}
