server:
  port: 9010
spring:
  cloud:
    stream:
      default-binder: pubsub
      bindings:
        input:
          destination: tweet
          group: log
      kafka:
        binder:
          brokers: localhost:32770
      gcp:
        pubsub:
          bindings:
            output:
              consumer:
                auto-create-resources: true
    gcp:
      pubsub:
        project-id: abekoh-sand
        credentials:
          scopes:
            - https://www.googleapis.com/auth/pubsub
slack:
  channel: "sandbox"
management:
  endpoints:
    web:
      exposure:
        include: "*"