namespace: messaging

replicaCount: 1

image:
  repository: gcr.io/abekoh-sand/gcp-messaging-sand-twitter-source
  tag: latest
  pullPolicy: IfNotPresent

spring:
  profiles: secret

secret:
  volumeName: secret-dir
  secretName: gcp-messaging-sand-twitter-source
  mountPath: /etc/secret
  fileNames:
    - application-secret.yml
    - spring-pubsub.json

service:
  externalIP: 34.68.226.31
