apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "{{ .Values.secret.mountPath }}/"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles }}
            - name: SPRING_CLOUD_GCP_PUBSUB_CREDENTIALS_LOCATION
              value: "file:{{ .Values.secret.mountPath }}/spring-pubsub.json"
          volumeMounts:
            - name: {{ .Values.secret.volumeName }}
              mountPath: {{ .Values.secret.mountPath }}
      volumes:
        {{- with .Values.secret }}
        - name: {{ .volumeName }}
          secret:
            secretName: {{ .secretName }}
            items:
              {{- range $fileName := .fileNames }}
              - key: {{ $fileName }}
                path: {{ $fileName }}
              {{- end}}
        {{- end }}
