server:
  port: 9000
spring:
  cloud:
    stream:
      default-binder: kafka
      # 出力先の個別設定
      bindings:
        twitter:
          destination: source-tweet
          contentType: application/json
      # デフォルトの出力先
      gcp:
        pubsub:
          bindings:
            output:
              consumer:
                auto-create-resources: true
      # kafka設定
      kafka:
        binder:
          brokers: localhost:32770
    gcp:
      pubsub:
        project-id: abekoh-sand
        credentials:
          scopes:
            - https://www.googleapis.com/auth/pubsub
twitter:
  stream:
    language: ja
    stream-type: sample
#    track: サトシ
management:
  endpoints:
    web:
      exposure:
        include: "*"
